# ==============================================================================
# DEPENDABOT CONFIGURATION
# ==============================================================================
# Purpose: Automatic dependency updates
# ==============================================================================

version: 2

updates:
  # ============================================================================
  # Go Dependencies
  # ============================================================================
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "devops-team"
    assignees:
      - "tech-lead"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    ignore:
      # Ignore major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # ============================================================================
  # Docker Images
  # ============================================================================
  - package-ecosystem: "docker"
    directory: "/dockerfiles"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"

  # ============================================================================
  # GitHub Actions
  # ============================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies"
      - "github-actions"

  # ============================================================================
  # Terraform
  # ============================================================================
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(terraform)"
    labels:
      - "dependencies"
      - "terraform"
