version: '3.8'
services:
  user-db:
    image: postgres:15-alpine
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service_db
    volumes:
    - user_db_data:/var/lib/postgresql/data
    networks:
    - ddd-micro-network
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  user-service:
    build:
      context: .
      dockerfile: dockerfiles/user.dockerfile
    container_name: user-service
    environment:
      PORT: 8080
      GIN_MODE: release
      DB_HOST: user-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: user_service_db
      DB_SSLMODE: disable
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    ports:
    - 8080:8080
    depends_on:
      user-db:
        condition: service_healthy
    networks:
    - ddd-micro-network
    restart: unless-stopped
  product-service:
    build:
      context: .
      dockerfile: dockerfiles/product.dockerfile
    container_name: product-service
    environment:
      HTTP_PORT: 8081
      GRPC_PORT: 9091
      GIN_MODE: release
      DB_HOST: product-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: product_service_db
      DB_SSLMODE: disable
      USER_SERVICE_URL: http://user-service:9090
    ports:
    - 8082:8081
    - 9092:9091
    depends_on:
      product-db:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
    - ddd-micro-network
    restart: unless-stopped
  product-db:
    image: postgres:15-alpine
    container_name: product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_service_db
    ports:
    - 5433:5432
    volumes:
    - product_db_data:/var/lib/postgresql/data
    networks:
    - ddd-micro-network
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  basket-db:
    image: postgres:15-alpine
    container_name: basket-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basket_service_db
    ports:
    - 5434:5432
    volumes:
    - basket_db_data:/var/lib/postgresql/data
    networks:
    - ddd-micro-network
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  payment-db:
    image: postgres:15-alpine
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_service_db
    ports:
    - 5435:5432
    volumes:
    - payment_db_data:/var/lib/postgresql/data
    networks:
    - ddd-micro-network
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  krakend:
    image: devopsfaith/krakend:latest
    container_name: krakend-gateway
    ports:
    - 8081:8080
    volumes:
    - "./gateways/krakend:/etc/krakend"
    depends_on:
    - user-service
    - product-service
    networks:
    - ddd-micro-network
networks:
  ddd-micro-network:
    driver: bridge
volumes:
  user_db_data: null
  product_db_data: null
  basket_db_data: null
  payment_db_data: null
