version: '3.8'
services:
  user-db:
    image: postgres:15-alpine
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service_db
    volumes:
    - user_db_data:/var/lib/postgresql/data
    networks:
    - ddd-micro-network
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  user-service:
    build:
      context: .
      dockerfile: dockerfiles/user.dockerfile
    container_name: user-service
    environment:
      PORT: 8080
      GIN_MODE: release
      DB_HOST: user-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: user_service_db
      DB_SSLMODE: disable
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    ports:
    - 8080:8080
    depends_on:
      user-db:
        condition: service_healthy
    networks:
    - ddd-micro-network
    restart: unless-stopped
  product-service:
    build:
      context: .
      dockerfile: dockerfiles/product.dockerfile
    container_name: product-service
    environment:
      HTTP_PORT: 8081
      GRPC_PORT: 9091
      GIN_MODE: release
      DB_HOST: product-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: product_service_db
      DB_SSLMODE: disable
      USER_SERVICE_URL: http://user-service:9090
    ports:
    - 8082:8081
    - 9092:9091
    depends_on:
      product-db:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
    - ddd-micro-network
    restart: unless-stopped
  product-db:
    image: postgres:15-alpine
    container_name: product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_service_db
    ports:
    - 5433:5432
    volumes:
    - product_db_data:/var/lib/postgresql/data
    networks:
    - ddd-micro-network
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  basket-db:
    image: postgres:15-alpine
    container_name: basket-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basket_service_db
    ports:
    - 5434:5432
    volumes:
    - basket_db_data:/var/lib/postgresql/data
    networks:
    - ddd-micro-network
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  payment-db:
    image: postgres:15-alpine
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_service_db
    ports:
    - 5435:5432
    volumes:
    - payment_db_data:/var/lib/postgresql/data
    networks:
    - ddd-micro-network
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  basket-service:
    build:
      context: .
      dockerfile: dockerfiles/basket.dockerfile
    container_name: basket-service
    environment:
      HTTP_PORT: 8083
      GRPC_PORT: 9093
      GIN_MODE: release
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: "0"
      USER_SERVICE_URL: user-service:9090
      PRODUCT_SERVICE_URL: product-service:9091
    ports:
    - 8083:8083
    - 9093:9093
    depends_on:
      redis:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
    networks:
    - ddd-micro-network
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
    - 6379:6379
    volumes:
    - redis_data:/data
    networks:
    - ddd-micro-network
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 10s
      timeout: 5s
      retries: 5
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
    - ddd-micro-network
    restart: unless-stopped
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
    - zookeeper
    ports:
    - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
    - ddd-micro-network
    restart: unless-stopped
  payment-service:
    build:
      context: .
      dockerfile: dockerfiles/payment.dockerfile
    container_name: payment-service
    environment:
      HTTP_PORT: 8084
      GIN_MODE: release
      DB_HOST: payment-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: payment_service_db
      DB_SSLMODE: disable
      USER_SERVICE_URL: user-service:9090
      PRODUCT_SERVICE_URL: product-service:9091
      BASKET_SERVICE_URL: basket-service:9093
      KAFKA_BROKERS: kafka:29092
    ports:
    - 8084:8084
    depends_on:
      payment-db:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      basket-service:
        condition: service_started
      kafka:
        condition: service_started
    networks:
    - ddd-micro-network
    restart: unless-stopped
  krakend:
    image: devopsfaith/krakend:latest
    container_name: krakend-gateway
    ports:
    - 8081:8080
    volumes:
    - "./gateways/krakend:/etc/krakend"
    depends_on:
    - user-service
    - product-service
    - basket-service
    - payment-service
    networks:
    - ddd-micro-network
networks:
  ddd-micro-network:
    driver: bridge
volumes:
  user_db_data: null
  product_db_data: null
  basket_db_data: null
  payment_db_data: null
  redis_data: null
