global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Product Service
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Basket Service
  - job_name: 'basket-service'
    static_configs:
      - targets: ['basket-service:8083']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8084']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # API Gateway (Krakend)
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8090']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
