// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ddd-micro/internal/basket/application"
	"github.com/ddd-micro/internal/basket/infrastructure"
	"github.com/ddd-micro/internal/basket/interfaces/grpc"
	"github.com/ddd-micro/internal/basket/interfaces/http"
	"github.com/gin-gonic/gin"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	// Infrastructure layer
	config := infrastructure.NewConfig()
	redisClient := infrastructure.NewRedisClient(config)
	userClient := infrastructure.NewUserClient(config)
	productClient := infrastructure.NewProductClient(config)
	basketRepository := infrastructure.NewBasketRepository(redisClient)
	
	// Application layer
	basketServiceCQRS := application.NewBasketServiceCQRS(basketRepository, userClient, productClient)
	
	// HTTP interface layer
	httpConfig := http.NewConfig()
	authMiddleware := http.NewAuthMiddleware(userClient)
	basketHandler := http.NewBasketHandler(basketServiceCQRS)
	userHandler := http.NewUserHandler(userClient)
	httpRouter := http.NewHTTPRouter(httpConfig, basketHandler, userHandler, authMiddleware)
	
	// gRPC interface layer
	basketServer := grpc.NewBasketServer(basketServiceCQRS)
	authInterceptor := grpc.NewAuthInterceptor(userClient)
	grpcServer := grpc.NewGRPCServer(basketServer, authInterceptor)
	
	// Main app
	app := NewApp(httpRouter, grpcServer)
	return app, func() {
	}, nil
}