// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ddd-micro/internal/basket/application"
	"github.com/ddd-micro/internal/basket/infrastructure"
	"github.com/ddd-micro/internal/basket/interfaces/http"
	"github.com/gin-gonic/gin"
)

// App represents the application dependencies
type App struct {
	HTTPRouter *gin.Engine
}

// NewApp creates a new App instance
func NewApp(httpRouter *gin.Engine) *App {
	return &App{
		HTTPRouter: httpRouter,
	}
}

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	config := infrastructure.ProvideConfig()
	databaseConfig := infrastructure.ProvideDatabaseConfig(config)
	database, err := infrastructure.ProvideDatabase(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	basketRepository := infrastructure.ProvideBasketRepository(database)
	userClient := infrastructure.ProvideUserClient(config)
	productClient := infrastructure.ProvideProductClient(config)
	basketServiceCQRS := application.NewBasketServiceCQRS(basketRepository, productClient)
	engine := http.NewHTTPRouter(basketServiceCQRS, userClient)
	app := NewApp(engine)
	return app, func() {
	}, nil
}