apiVersion: v2
name: ddd-micro
description: DDD Microservices Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "12.1.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: postgresql-product
    version: "0.1.0"
    repository: "file://charts/postgresql-product"
    condition: postgresql-product.enabled
  - name: postgresql-basket
    version: "0.1.0"
    repository: "file://charts/postgresql-basket"
    condition: postgresql-basket.enabled
  - name: postgresql-payment
    version: "0.1.0"
    repository: "file://charts/postgresql-payment"
    condition: postgresql-payment.enabled
  - name: redis
    version: "0.1.0"
    repository: "file://charts/redis"
    condition: redis.enabled
  - name: kafka
    version: "0.1.0"
    repository: "file://charts/kafka"
    condition: kafka.enabled
