// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/basket/basket.proto

package basket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBasketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBasketRequest) Reset() {
	*x = CreateBasketRequest{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketRequest) ProtoMessage() {}

func (x *CreateBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketRequest.ProtoReflect.Descriptor instead.
func (*CreateBasketRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBasketRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBasketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasketRequest) Reset() {
	*x = GetBasketRequest{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketRequest) ProtoMessage() {}

func (x *GetBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketRequest.ProtoReflect.Descriptor instead.
func (*GetBasketRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{1}
}

func (x *GetBasketRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{2}
}

func (x *AddItemRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddItemRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddItemRequest) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateItemRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateItemRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveItemRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveItemRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ClearBasketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBasketRequest) Reset() {
	*x = ClearBasketRequest{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBasketRequest) ProtoMessage() {}

func (x *ClearBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBasketRequest.ProtoReflect.Descriptor instead.
func (*ClearBasketRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{5}
}

func (x *ClearBasketRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserBasketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBasketRequest) Reset() {
	*x = GetUserBasketRequest{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasketRequest) ProtoMessage() {}

func (x *GetUserBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasketRequest.ProtoReflect.Descriptor instead.
func (*GetUserBasketRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserBasketRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteUserBasketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserBasketRequest) Reset() {
	*x = DeleteUserBasketRequest{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserBasketRequest) ProtoMessage() {}

func (x *DeleteUserBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserBasketRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserBasketRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserBasketRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CleanupExpiredBasketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupExpiredBasketsRequest) Reset() {
	*x = CleanupExpiredBasketsRequest{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupExpiredBasketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupExpiredBasketsRequest) ProtoMessage() {}

func (x *CleanupExpiredBasketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupExpiredBasketsRequest.ProtoReflect.Descriptor instead.
func (*CleanupExpiredBasketsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{8}
}

type BasketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*BasketItem          `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total         float64                `protobuf:"fixed64,4,opt,name=total,proto3" json:"total,omitempty"`
	ItemCount     int32                  `protobuf:"varint,5,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IsExpired     bool                   `protobuf:"varint,9,opt,name=is_expired,json=isExpired,proto3" json:"is_expired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasketResponse) Reset() {
	*x = BasketResponse{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketResponse) ProtoMessage() {}

func (x *BasketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketResponse.ProtoReflect.Descriptor instead.
func (*BasketResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{9}
}

func (x *BasketResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BasketResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BasketResponse) GetItems() []*BasketItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BasketResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BasketResponse) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *BasketResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BasketResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BasketResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *BasketResponse) GetIsExpired() bool {
	if x != nil {
		return x.IsExpired
	}
	return false
}

type BasketItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasketItem) Reset() {
	*x = BasketItem{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketItem) ProtoMessage() {}

func (x *BasketItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketItem.ProtoReflect.Descriptor instead.
func (*BasketItem) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{10}
}

func (x *BasketItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BasketItem) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *BasketItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BasketItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *BasketItem) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *BasketItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BasketItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ClearBasketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBasketResponse) Reset() {
	*x = ClearBasketResponse{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBasketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBasketResponse) ProtoMessage() {}

func (x *ClearBasketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBasketResponse.ProtoReflect.Descriptor instead.
func (*ClearBasketResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{11}
}

func (x *ClearBasketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearBasketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteUserBasketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserBasketResponse) Reset() {
	*x = DeleteUserBasketResponse{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserBasketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserBasketResponse) ProtoMessage() {}

func (x *DeleteUserBasketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserBasketResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserBasketResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserBasketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteUserBasketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CleanupExpiredBasketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CleanedCount  int32                  `protobuf:"varint,3,opt,name=cleaned_count,json=cleanedCount,proto3" json:"cleaned_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupExpiredBasketsResponse) Reset() {
	*x = CleanupExpiredBasketsResponse{}
	mi := &file_api_proto_basket_basket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupExpiredBasketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupExpiredBasketsResponse) ProtoMessage() {}

func (x *CleanupExpiredBasketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_basket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupExpiredBasketsResponse.ProtoReflect.Descriptor instead.
func (*CleanupExpiredBasketsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_basket_proto_rawDescGZIP(), []int{13}
}

func (x *CleanupExpiredBasketsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CleanupExpiredBasketsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CleanupExpiredBasketsResponse) GetCleanedCount() int32 {
	if x != nil {
		return x.CleanedCount
	}
	return 0
}

var File_api_proto_basket_basket_proto protoreflect.FileDescriptor

const file_api_proto_basket_basket_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/basket/basket.proto\x12\x06basket\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x13CreateBasketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"+\n" +
	"\x10GetBasketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"\x83\x01\n" +
	"\x0eAddItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\"g\n" +
	"\x11UpdateItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"K\n" +
	"\x11RemoveItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\"-\n" +
	"\x12ClearBasketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"/\n" +
	"\x14GetUserBasketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"2\n" +
	"\x17DeleteUserBasketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"\x1e\n" +
	"\x1cCleanupExpiredBasketsRequest\"\xe8\x02\n" +
	"\x0eBasketResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12(\n" +
	"\x05items\x18\x03 \x03(\v2\x12.basket.BasketItemR\x05items\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x01R\x05total\x12\x1d\n" +
	"\n" +
	"item_count\x18\x05 \x01(\x05R\titemCount\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"is_expired\x18\t \x01(\bR\tisExpired\"\x8d\x02\n" +
	"\n" +
	"BasketItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x01R\n" +
	"totalPrice\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"I\n" +
	"\x13ClearBasketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x18DeleteUserBasketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"x\n" +
	"\x1dCleanupExpiredBasketsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rcleaned_count\x18\x03 \x01(\x05R\fcleanedCount2\x9c\x05\n" +
	"\rBasketService\x12C\n" +
	"\fCreateBasket\x12\x1b.basket.CreateBasketRequest\x1a\x16.basket.BasketResponse\x12=\n" +
	"\tGetBasket\x12\x18.basket.GetBasketRequest\x1a\x16.basket.BasketResponse\x129\n" +
	"\aAddItem\x12\x16.basket.AddItemRequest\x1a\x16.basket.BasketResponse\x12?\n" +
	"\n" +
	"UpdateItem\x12\x19.basket.UpdateItemRequest\x1a\x16.basket.BasketResponse\x12?\n" +
	"\n" +
	"RemoveItem\x12\x19.basket.RemoveItemRequest\x1a\x16.basket.BasketResponse\x12F\n" +
	"\vClearBasket\x12\x1a.basket.ClearBasketRequest\x1a\x1b.basket.ClearBasketResponse\x12E\n" +
	"\rGetUserBasket\x12\x1c.basket.GetUserBasketRequest\x1a\x16.basket.BasketResponse\x12U\n" +
	"\x10DeleteUserBasket\x12\x1f.basket.DeleteUserBasketRequest\x1a .basket.DeleteUserBasketResponse\x12d\n" +
	"\x15CleanupExpiredBaskets\x12$.basket.CleanupExpiredBasketsRequest\x1a%.basket.CleanupExpiredBasketsResponseB'Z%github.com/ddd-micro/api/proto/basketb\x06proto3"

var (
	file_api_proto_basket_basket_proto_rawDescOnce sync.Once
	file_api_proto_basket_basket_proto_rawDescData []byte
)

func file_api_proto_basket_basket_proto_rawDescGZIP() []byte {
	file_api_proto_basket_basket_proto_rawDescOnce.Do(func() {
		file_api_proto_basket_basket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_basket_basket_proto_rawDesc), len(file_api_proto_basket_basket_proto_rawDesc)))
	})
	return file_api_proto_basket_basket_proto_rawDescData
}

var file_api_proto_basket_basket_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_basket_basket_proto_goTypes = []any{
	(*CreateBasketRequest)(nil),           // 0: basket.CreateBasketRequest
	(*GetBasketRequest)(nil),              // 1: basket.GetBasketRequest
	(*AddItemRequest)(nil),                // 2: basket.AddItemRequest
	(*UpdateItemRequest)(nil),             // 3: basket.UpdateItemRequest
	(*RemoveItemRequest)(nil),             // 4: basket.RemoveItemRequest
	(*ClearBasketRequest)(nil),            // 5: basket.ClearBasketRequest
	(*GetUserBasketRequest)(nil),          // 6: basket.GetUserBasketRequest
	(*DeleteUserBasketRequest)(nil),       // 7: basket.DeleteUserBasketRequest
	(*CleanupExpiredBasketsRequest)(nil),  // 8: basket.CleanupExpiredBasketsRequest
	(*BasketResponse)(nil),                // 9: basket.BasketResponse
	(*BasketItem)(nil),                    // 10: basket.BasketItem
	(*ClearBasketResponse)(nil),           // 11: basket.ClearBasketResponse
	(*DeleteUserBasketResponse)(nil),      // 12: basket.DeleteUserBasketResponse
	(*CleanupExpiredBasketsResponse)(nil), // 13: basket.CleanupExpiredBasketsResponse
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
}
var file_api_proto_basket_basket_proto_depIdxs = []int32{
	10, // 0: basket.BasketResponse.items:type_name -> basket.BasketItem
	14, // 1: basket.BasketResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: basket.BasketResponse.updated_at:type_name -> google.protobuf.Timestamp
	14, // 3: basket.BasketResponse.expires_at:type_name -> google.protobuf.Timestamp
	14, // 4: basket.BasketItem.created_at:type_name -> google.protobuf.Timestamp
	14, // 5: basket.BasketItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: basket.BasketService.CreateBasket:input_type -> basket.CreateBasketRequest
	1,  // 7: basket.BasketService.GetBasket:input_type -> basket.GetBasketRequest
	2,  // 8: basket.BasketService.AddItem:input_type -> basket.AddItemRequest
	3,  // 9: basket.BasketService.UpdateItem:input_type -> basket.UpdateItemRequest
	4,  // 10: basket.BasketService.RemoveItem:input_type -> basket.RemoveItemRequest
	5,  // 11: basket.BasketService.ClearBasket:input_type -> basket.ClearBasketRequest
	6,  // 12: basket.BasketService.GetUserBasket:input_type -> basket.GetUserBasketRequest
	7,  // 13: basket.BasketService.DeleteUserBasket:input_type -> basket.DeleteUserBasketRequest
	8,  // 14: basket.BasketService.CleanupExpiredBaskets:input_type -> basket.CleanupExpiredBasketsRequest
	9,  // 15: basket.BasketService.CreateBasket:output_type -> basket.BasketResponse
	9,  // 16: basket.BasketService.GetBasket:output_type -> basket.BasketResponse
	9,  // 17: basket.BasketService.AddItem:output_type -> basket.BasketResponse
	9,  // 18: basket.BasketService.UpdateItem:output_type -> basket.BasketResponse
	9,  // 19: basket.BasketService.RemoveItem:output_type -> basket.BasketResponse
	11, // 20: basket.BasketService.ClearBasket:output_type -> basket.ClearBasketResponse
	9,  // 21: basket.BasketService.GetUserBasket:output_type -> basket.BasketResponse
	12, // 22: basket.BasketService.DeleteUserBasket:output_type -> basket.DeleteUserBasketResponse
	13, // 23: basket.BasketService.CleanupExpiredBaskets:output_type -> basket.CleanupExpiredBasketsResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_basket_basket_proto_init() }
func file_api_proto_basket_basket_proto_init() {
	if File_api_proto_basket_basket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_basket_basket_proto_rawDesc), len(file_api_proto_basket_basket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_basket_basket_proto_goTypes,
		DependencyIndexes: file_api_proto_basket_basket_proto_depIdxs,
		MessageInfos:      file_api_proto_basket_basket_proto_msgTypes,
	}.Build()
	File_api_proto_basket_basket_proto = out.File
	file_api_proto_basket_basket_proto_goTypes = nil
	file_api_proto_basket_basket_proto_depIdxs = nil
}
