// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/basket/basket.proto

package basket

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BasketService_CreateBasket_FullMethodName          = "/basket.BasketService/CreateBasket"
	BasketService_GetBasket_FullMethodName             = "/basket.BasketService/GetBasket"
	BasketService_AddItem_FullMethodName               = "/basket.BasketService/AddItem"
	BasketService_UpdateItem_FullMethodName            = "/basket.BasketService/UpdateItem"
	BasketService_RemoveItem_FullMethodName            = "/basket.BasketService/RemoveItem"
	BasketService_ClearBasket_FullMethodName           = "/basket.BasketService/ClearBasket"
	BasketService_GetUserBasket_FullMethodName         = "/basket.BasketService/GetUserBasket"
	BasketService_DeleteUserBasket_FullMethodName      = "/basket.BasketService/DeleteUserBasket"
	BasketService_CleanupExpiredBaskets_FullMethodName = "/basket.BasketService/CleanupExpiredBaskets"
)

// BasketServiceClient is the client API for BasketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Basket service definition
type BasketServiceClient interface {
	// Create a new basket for a user
	CreateBasket(ctx context.Context, in *CreateBasketRequest, opts ...grpc.CallOption) (*BasketResponse, error)
	// Get user's basket
	GetBasket(ctx context.Context, in *GetBasketRequest, opts ...grpc.CallOption) (*BasketResponse, error)
	// Add item to basket
	AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*BasketResponse, error)
	// Update item quantity in basket
	UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*BasketResponse, error)
	// Remove item from basket
	RemoveItem(ctx context.Context, in *RemoveItemRequest, opts ...grpc.CallOption) (*BasketResponse, error)
	// Clear all items from basket
	ClearBasket(ctx context.Context, in *ClearBasketRequest, opts ...grpc.CallOption) (*ClearBasketResponse, error)
	// Admin operations
	GetUserBasket(ctx context.Context, in *GetUserBasketRequest, opts ...grpc.CallOption) (*BasketResponse, error)
	DeleteUserBasket(ctx context.Context, in *DeleteUserBasketRequest, opts ...grpc.CallOption) (*DeleteUserBasketResponse, error)
	CleanupExpiredBaskets(ctx context.Context, in *CleanupExpiredBasketsRequest, opts ...grpc.CallOption) (*CleanupExpiredBasketsResponse, error)
}

type basketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBasketServiceClient(cc grpc.ClientConnInterface) BasketServiceClient {
	return &basketServiceClient{cc}
}

func (c *basketServiceClient) CreateBasket(ctx context.Context, in *CreateBasketRequest, opts ...grpc.CallOption) (*BasketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasketResponse)
	err := c.cc.Invoke(ctx, BasketService_CreateBasket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basketServiceClient) GetBasket(ctx context.Context, in *GetBasketRequest, opts ...grpc.CallOption) (*BasketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasketResponse)
	err := c.cc.Invoke(ctx, BasketService_GetBasket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basketServiceClient) AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*BasketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasketResponse)
	err := c.cc.Invoke(ctx, BasketService_AddItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basketServiceClient) UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*BasketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasketResponse)
	err := c.cc.Invoke(ctx, BasketService_UpdateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basketServiceClient) RemoveItem(ctx context.Context, in *RemoveItemRequest, opts ...grpc.CallOption) (*BasketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasketResponse)
	err := c.cc.Invoke(ctx, BasketService_RemoveItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basketServiceClient) ClearBasket(ctx context.Context, in *ClearBasketRequest, opts ...grpc.CallOption) (*ClearBasketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearBasketResponse)
	err := c.cc.Invoke(ctx, BasketService_ClearBasket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basketServiceClient) GetUserBasket(ctx context.Context, in *GetUserBasketRequest, opts ...grpc.CallOption) (*BasketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasketResponse)
	err := c.cc.Invoke(ctx, BasketService_GetUserBasket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basketServiceClient) DeleteUserBasket(ctx context.Context, in *DeleteUserBasketRequest, opts ...grpc.CallOption) (*DeleteUserBasketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserBasketResponse)
	err := c.cc.Invoke(ctx, BasketService_DeleteUserBasket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basketServiceClient) CleanupExpiredBaskets(ctx context.Context, in *CleanupExpiredBasketsRequest, opts ...grpc.CallOption) (*CleanupExpiredBasketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupExpiredBasketsResponse)
	err := c.cc.Invoke(ctx, BasketService_CleanupExpiredBaskets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasketServiceServer is the server API for BasketService service.
// All implementations must embed UnimplementedBasketServiceServer
// for forward compatibility.
//
// Basket service definition
type BasketServiceServer interface {
	// Create a new basket for a user
	CreateBasket(context.Context, *CreateBasketRequest) (*BasketResponse, error)
	// Get user's basket
	GetBasket(context.Context, *GetBasketRequest) (*BasketResponse, error)
	// Add item to basket
	AddItem(context.Context, *AddItemRequest) (*BasketResponse, error)
	// Update item quantity in basket
	UpdateItem(context.Context, *UpdateItemRequest) (*BasketResponse, error)
	// Remove item from basket
	RemoveItem(context.Context, *RemoveItemRequest) (*BasketResponse, error)
	// Clear all items from basket
	ClearBasket(context.Context, *ClearBasketRequest) (*ClearBasketResponse, error)
	// Admin operations
	GetUserBasket(context.Context, *GetUserBasketRequest) (*BasketResponse, error)
	DeleteUserBasket(context.Context, *DeleteUserBasketRequest) (*DeleteUserBasketResponse, error)
	CleanupExpiredBaskets(context.Context, *CleanupExpiredBasketsRequest) (*CleanupExpiredBasketsResponse, error)
	mustEmbedUnimplementedBasketServiceServer()
}

// UnimplementedBasketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBasketServiceServer struct{}

func (UnimplementedBasketServiceServer) CreateBasket(context.Context, *CreateBasketRequest) (*BasketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBasket not implemented")
}
func (UnimplementedBasketServiceServer) GetBasket(context.Context, *GetBasketRequest) (*BasketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBasket not implemented")
}
func (UnimplementedBasketServiceServer) AddItem(context.Context, *AddItemRequest) (*BasketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItem not implemented")
}
func (UnimplementedBasketServiceServer) UpdateItem(context.Context, *UpdateItemRequest) (*BasketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItem not implemented")
}
func (UnimplementedBasketServiceServer) RemoveItem(context.Context, *RemoveItemRequest) (*BasketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveItem not implemented")
}
func (UnimplementedBasketServiceServer) ClearBasket(context.Context, *ClearBasketRequest) (*ClearBasketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearBasket not implemented")
}
func (UnimplementedBasketServiceServer) GetUserBasket(context.Context, *GetUserBasketRequest) (*BasketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBasket not implemented")
}
func (UnimplementedBasketServiceServer) DeleteUserBasket(context.Context, *DeleteUserBasketRequest) (*DeleteUserBasketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserBasket not implemented")
}
func (UnimplementedBasketServiceServer) CleanupExpiredBaskets(context.Context, *CleanupExpiredBasketsRequest) (*CleanupExpiredBasketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanupExpiredBaskets not implemented")
}
func (UnimplementedBasketServiceServer) mustEmbedUnimplementedBasketServiceServer() {}
func (UnimplementedBasketServiceServer) testEmbeddedByValue()                       {}

// UnsafeBasketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BasketServiceServer will
// result in compilation errors.
type UnsafeBasketServiceServer interface {
	mustEmbedUnimplementedBasketServiceServer()
}

func RegisterBasketServiceServer(s grpc.ServiceRegistrar, srv BasketServiceServer) {
	// If the following call pancis, it indicates UnimplementedBasketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BasketService_ServiceDesc, srv)
}

func _BasketService_CreateBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBasketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketServiceServer).CreateBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketService_CreateBasket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketServiceServer).CreateBasket(ctx, req.(*CreateBasketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasketService_GetBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBasketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketServiceServer).GetBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketService_GetBasket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketServiceServer).GetBasket(ctx, req.(*GetBasketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasketService_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketServiceServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketService_AddItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketServiceServer).AddItem(ctx, req.(*AddItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasketService_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketServiceServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketService_UpdateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketServiceServer).UpdateItem(ctx, req.(*UpdateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasketService_RemoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketServiceServer).RemoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketService_RemoveItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketServiceServer).RemoveItem(ctx, req.(*RemoveItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasketService_ClearBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearBasketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketServiceServer).ClearBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketService_ClearBasket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketServiceServer).ClearBasket(ctx, req.(*ClearBasketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasketService_GetUserBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBasketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketServiceServer).GetUserBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketService_GetUserBasket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketServiceServer).GetUserBasket(ctx, req.(*GetUserBasketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasketService_DeleteUserBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserBasketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketServiceServer).DeleteUserBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketService_DeleteUserBasket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketServiceServer).DeleteUserBasket(ctx, req.(*DeleteUserBasketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasketService_CleanupExpiredBaskets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupExpiredBasketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasketServiceServer).CleanupExpiredBaskets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasketService_CleanupExpiredBaskets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasketServiceServer).CleanupExpiredBaskets(ctx, req.(*CleanupExpiredBasketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BasketService_ServiceDesc is the grpc.ServiceDesc for BasketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BasketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basket.BasketService",
	HandlerType: (*BasketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBasket",
			Handler:    _BasketService_CreateBasket_Handler,
		},
		{
			MethodName: "GetBasket",
			Handler:    _BasketService_GetBasket_Handler,
		},
		{
			MethodName: "AddItem",
			Handler:    _BasketService_AddItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _BasketService_UpdateItem_Handler,
		},
		{
			MethodName: "RemoveItem",
			Handler:    _BasketService_RemoveItem_Handler,
		},
		{
			MethodName: "ClearBasket",
			Handler:    _BasketService_ClearBasket_Handler,
		},
		{
			MethodName: "GetUserBasket",
			Handler:    _BasketService_GetUserBasket_Handler,
		},
		{
			MethodName: "DeleteUserBasket",
			Handler:    _BasketService_DeleteUserBasket_Handler,
		},
		{
			MethodName: "CleanupExpiredBaskets",
			Handler:    _BasketService_CleanupExpiredBaskets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/basket/basket.proto",
}
