package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/ddd-micro/internal/payment/infrastructure/database"
	"github.com/ddd-micro/internal/payment/interfaces/http"
	"github.com/gin-gonic/gin"
)

func main() {
	// Initialize application
	app, cleanup, err := InitializeApp()
	if err != nil {
		log.Fatalf("Failed to initialize app: %v", err)
	}
	defer cleanup()

	// Set Gin mode
	gin.SetMode(gin.ReleaseMode)

	// Start HTTP server
	httpPort := os.Getenv("HTTP_PORT")
	if httpPort == "" {
		httpPort = "8084"
	}

	log.Printf("Starting HTTP Server on port %s...", httpPort)
	if err := app.HTTPRouter.Run(":" + httpPort); err != nil {
		log.Fatalf("HTTP server failed to start: %v", err)
	}

	// Wait for interrupt signal to gracefully shutdown the server
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Shutting down server...")

	// Create a deadline to wait for
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// Shutdown HTTP server
	log.Println("Stopping HTTP server...")
	// Note: Gin doesn't have built-in graceful shutdown, but we can add it if needed

	log.Println("Server stopped")
}

// App represents the application dependencies
type App struct {
	HTTPRouter *gin.Engine
}

// InitializeApp initializes all application dependencies using Wire
func InitializeApp() (*App, func(), error) {
	// This will be generated by Wire
	panic("wire: not implemented")
}
