kafka:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  zookeeper:
    enabled: true
    persistence:
      enabled: true
      size: 5Gi
