{{- if .Values.basketService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: basket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-service
  template:
    metadata:
      labels:
        app: basket-service
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: basket-service
        image: "{{ .Values.global.imageRegistry }}{{ .Values.basketService.image.repository }}:{{ .Values.basketService.image.tag }}"
        imagePullPolicy: {{ .Values.basketService.image.pullPolicy }}
        ports:
        - containerPort: 8083
          name: http
        - containerPort: 9093
          name: grpc
        env:
        - name: HTTP_PORT
          value: "8083"
        - name: GRPC_PORT
          value: "9093"
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: ddd-micro-config
              key: GIN_MODE
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: ddd-micro-config
              key: REDIS_PASSWORD
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: ddd-micro-config
              key: REDIS_DB
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ddd-micro-config
              key: USER_SERVICE_URL
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ddd-micro-config
              key: PRODUCT_SERVICE_URL
        resources:
          {{- toYaml .Values.basketService.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: basket-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: basket-service
spec:
  type: {{ .Values.basketService.service.type }}
  ports:
  - port: {{ .Values.basketService.service.httpPort }}
    targetPort: 8083
    protocol: TCP
    name: http
  - port: {{ .Values.basketService.service.grpcPort }}
    targetPort: 9093
    protocol: TCP
    name: grpc
  selector:
    app: basket-service
{{- end }}
