{{- if .Values.productService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: product-service
        image: "{{ .Values.global.imageRegistry }}{{ .Values.productService.image.repository }}:{{ .Values.productService.image.tag }}"
        imagePullPolicy: {{ .Values.productService.image.pullPolicy }}
        ports:
        - containerPort: 8081
          name: http
        - containerPort: 9091
          name: grpc
        env:
        - name: HTTP_PORT
          value: "8081"
        - name: GRPC_PORT
          value: "9091"
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: ddd-micro-config
              key: GIN_MODE
        - name: DB_HOST
          value: "postgresql-product"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: ddd-micro-config
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: ddd-micro-config
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          value: "product_service_db"
        - name: DB_SSLMODE
          valueFrom:
            configMapKeyRef:
              name: ddd-micro-config
              key: DB_SSLMODE
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ddd-micro-config
              key: USER_SERVICE_URL
        resources:
          {{- toYaml .Values.productService.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: product-service
spec:
  type: {{ .Values.productService.service.type }}
  ports:
  - port: {{ .Values.productService.service.httpPort }}
    targetPort: 8081
    protocol: TCP
    name: http
  - port: {{ .Values.productService.service.grpcPort }}
    targetPort: 9091
    protocol: TCP
    name: grpc
  selector:
    app: product-service
{{- end }}
