---
# Debian/Ubuntu specific tasks

- name: "Update package cache"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Install required packages"
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    state: present

- name: "Add Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: "Add Kubernetes GPG key"
  shell: |
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  args:
    creates: /etc/apt/sources.list.d/kubernetes.list

- name: "Add Kubernetes repository"
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    update_cache: yes

- name: "Install containerd"
  package:
    name: containerd.io
    state: present

- name: "Install Kubernetes packages"
  package:
    name:
      - kubelet={{ k8s_version }}-00
      - kubeadm={{ k8s_version }}-00
      - kubectl={{ k8s_version }}-00
    state: present
    allow_downgrade: yes

- name: "Hold Kubernetes packages"
  dpkg_selections:
    name:
      - kubelet
      - kubeadm
      - kubectl
    selection: hold
