// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ddd-micro/internal/user/application"
	"github.com/ddd-micro/internal/user/application/command"
	"github.com/ddd-micro/internal/user/application/query"
	"github.com/ddd-micro/internal/user/infrastructure"
	"github.com/ddd-micro/internal/user/infrastructure/database"
	"github.com/ddd-micro/internal/user/interfaces/http"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// InitializeApp initializes the entire application with all dependencies
func InitializeApp() (*App, error) {
	config := infrastructure.ProvideConfig()
	databaseConfig := infrastructure.ProvideDatabaseConfig(config)
	database, err := infrastructure.ProvideDatabase(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := infrastructure.ProvideUserRepository(database)
	createUserHandler := command.NewCreateUserHandler(userRepository)
	updateUserHandler := command.NewUpdateUserHandler(userRepository)
	updateUserByAdminHandler := command.NewUpdateUserByAdminHandler(userRepository)
	deleteUserHandler := command.NewDeleteUserHandler(userRepository)
	changePasswordHandler := command.NewChangePasswordHandler(userRepository)
	assignRoleHandler := command.NewAssignRoleHandler(userRepository)
	string2 := infrastructure.ProvideJWTSecret()
	duration := application.ProvideTokenDuration()
	loginHandler := application.ProvideLoginHandler(userRepository, string2, duration)
	getUserByIDHandler := query.NewGetUserByIDHandler(userRepository)
	getUserByEmailHandler := query.NewGetUserByEmailHandler(userRepository)
	listUsersHandler := query.NewListUsersHandler(userRepository)
	jwtHelper := application.ProvideJWTHelper(string2, duration)
	userServiceCQRS := application.ProvideUserServiceCQRS(createUserHandler, updateUserHandler, updateUserByAdminHandler, deleteUserHandler, changePasswordHandler, assignRoleHandler, loginHandler, getUserByIDHandler, getUserByEmailHandler, listUsersHandler, jwtHelper)
	engine := http.ProvideRouter(userServiceCQRS)
	app := NewApp(engine, userServiceCQRS, database)
	return app, nil
}

// wire.go:

// App holds all application dependencies
type App struct {
	Router      *gin.Engine
	UserService *application.UserServiceCQRS
	Database    *database.Database
}

// NewApp creates a new App instance
func NewApp(
	router *gin.Engine,
	userService *application.UserServiceCQRS,
	db *database.Database,
) *App {
	return &App{
		Router:      router,
		UserService: userService,
		Database:    db,
	}
}
