// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/product/product.proto

package productpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product message
type Product struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription string                 `protobuf:"bytes,4,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Price            float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ComparePrice     float64                `protobuf:"fixed64,6,opt,name=compare_price,json=comparePrice,proto3" json:"compare_price,omitempty"`
	CostPrice        float64                `protobuf:"fixed64,7,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	Stock            int32                  `protobuf:"varint,8,opt,name=stock,proto3" json:"stock,omitempty"`
	MinStock         int32                  `protobuf:"varint,9,opt,name=min_stock,json=minStock,proto3" json:"min_stock,omitempty"`
	MaxStock         int32                  `protobuf:"varint,10,opt,name=max_stock,json=maxStock,proto3" json:"max_stock,omitempty"`
	Category         string                 `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory      string                 `protobuf:"bytes,12,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	Brand            string                 `protobuf:"bytes,13,opt,name=brand,proto3" json:"brand,omitempty"`
	Sku              string                 `protobuf:"bytes,14,opt,name=sku,proto3" json:"sku,omitempty"`
	Barcode          string                 `protobuf:"bytes,15,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Weight           float64                `protobuf:"fixed64,16,opt,name=weight,proto3" json:"weight,omitempty"`
	Dimensions       string                 `protobuf:"bytes,17,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Color            string                 `protobuf:"bytes,18,opt,name=color,proto3" json:"color,omitempty"`
	Size             string                 `protobuf:"bytes,19,opt,name=size,proto3" json:"size,omitempty"`
	Material         string                 `protobuf:"bytes,20,opt,name=material,proto3" json:"material,omitempty"`
	Tags             string                 `protobuf:"bytes,21,opt,name=tags,proto3" json:"tags,omitempty"`
	Images           string                 `protobuf:"bytes,22,opt,name=images,proto3" json:"images,omitempty"`
	IsActive         bool                   `protobuf:"varint,23,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsDigital        bool                   `protobuf:"varint,24,opt,name=is_digital,json=isDigital,proto3" json:"is_digital,omitempty"`
	IsFeatured       bool                   `protobuf:"varint,25,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	IsOnSale         bool                   `protobuf:"varint,26,opt,name=is_on_sale,json=isOnSale,proto3" json:"is_on_sale,omitempty"`
	SortOrder        int32                  `protobuf:"varint,27,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	ViewCount        int32                  `protobuf:"varint,28,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,29,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,30,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_proto_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetComparePrice() float64 {
	if x != nil {
		return x.ComparePrice
	}
	return 0
}

func (x *Product) GetCostPrice() float64 {
	if x != nil {
		return x.CostPrice
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetMinStock() int32 {
	if x != nil {
		return x.MinStock
	}
	return 0
}

func (x *Product) GetMaxStock() int32 {
	if x != nil {
		return x.MaxStock
	}
	return 0
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *Product) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Product) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Product) GetDimensions() string {
	if x != nil {
		return x.Dimensions
	}
	return ""
}

func (x *Product) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Product) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Product) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *Product) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Product) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Product) GetIsDigital() bool {
	if x != nil {
		return x.IsDigital
	}
	return false
}

func (x *Product) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *Product) GetIsOnSale() bool {
	if x != nil {
		return x.IsOnSale
	}
	return false
}

func (x *Product) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Product) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateProduct messages
type CreateProductRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription string                 `protobuf:"bytes,3,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Price            float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	ComparePrice     float64                `protobuf:"fixed64,5,opt,name=compare_price,json=comparePrice,proto3" json:"compare_price,omitempty"`
	CostPrice        float64                `protobuf:"fixed64,6,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	Stock            int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	MinStock         int32                  `protobuf:"varint,8,opt,name=min_stock,json=minStock,proto3" json:"min_stock,omitempty"`
	MaxStock         int32                  `protobuf:"varint,9,opt,name=max_stock,json=maxStock,proto3" json:"max_stock,omitempty"`
	Category         string                 `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory      string                 `protobuf:"bytes,11,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	Brand            string                 `protobuf:"bytes,12,opt,name=brand,proto3" json:"brand,omitempty"`
	Sku              string                 `protobuf:"bytes,13,opt,name=sku,proto3" json:"sku,omitempty"`
	Barcode          string                 `protobuf:"bytes,14,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Weight           float64                `protobuf:"fixed64,15,opt,name=weight,proto3" json:"weight,omitempty"`
	Dimensions       string                 `protobuf:"bytes,16,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Color            string                 `protobuf:"bytes,17,opt,name=color,proto3" json:"color,omitempty"`
	Size             string                 `protobuf:"bytes,18,opt,name=size,proto3" json:"size,omitempty"`
	Material         string                 `protobuf:"bytes,19,opt,name=material,proto3" json:"material,omitempty"`
	Tags             string                 `protobuf:"bytes,20,opt,name=tags,proto3" json:"tags,omitempty"`
	Images           string                 `protobuf:"bytes,21,opt,name=images,proto3" json:"images,omitempty"`
	IsDigital        bool                   `protobuf:"varint,22,opt,name=is_digital,json=isDigital,proto3" json:"is_digital,omitempty"`
	IsFeatured       bool                   `protobuf:"varint,23,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	IsOnSale         bool                   `protobuf:"varint,24,opt,name=is_on_sale,json=isOnSale,proto3" json:"is_on_sale,omitempty"`
	SortOrder        int32                  `protobuf:"varint,25,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetComparePrice() float64 {
	if x != nil {
		return x.ComparePrice
	}
	return 0
}

func (x *CreateProductRequest) GetCostPrice() float64 {
	if x != nil {
		return x.CostPrice
	}
	return 0
}

func (x *CreateProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductRequest) GetMinStock() int32 {
	if x != nil {
		return x.MinStock
	}
	return 0
}

func (x *CreateProductRequest) GetMaxStock() int32 {
	if x != nil {
		return x.MaxStock
	}
	return 0
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *CreateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateProductRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *CreateProductRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateProductRequest) GetDimensions() string {
	if x != nil {
		return x.Dimensions
	}
	return ""
}

func (x *CreateProductRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateProductRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *CreateProductRequest) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *CreateProductRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *CreateProductRequest) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *CreateProductRequest) GetIsDigital() bool {
	if x != nil {
		return x.IsDigital
	}
	return false
}

func (x *CreateProductRequest) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *CreateProductRequest) GetIsOnSale() bool {
	if x != nil {
		return x.IsOnSale
	}
	return false
}

func (x *CreateProductRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_api_proto_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// GetProduct messages
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductBySKURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductBySKURequest) Reset() {
	*x = GetProductBySKURequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductBySKURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductBySKURequest) ProtoMessage() {}

func (x *GetProductBySKURequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductBySKURequest.ProtoReflect.Descriptor instead.
func (*GetProductBySKURequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductBySKURequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

// UpdateProduct messages
type UpdateProductRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description      *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ShortDescription *string                `protobuf:"bytes,4,opt,name=short_description,json=shortDescription,proto3,oneof" json:"short_description,omitempty"`
	Price            *float64               `protobuf:"fixed64,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	ComparePrice     *float64               `protobuf:"fixed64,6,opt,name=compare_price,json=comparePrice,proto3,oneof" json:"compare_price,omitempty"`
	CostPrice        *float64               `protobuf:"fixed64,7,opt,name=cost_price,json=costPrice,proto3,oneof" json:"cost_price,omitempty"`
	Stock            *int32                 `protobuf:"varint,8,opt,name=stock,proto3,oneof" json:"stock,omitempty"`
	MinStock         *int32                 `protobuf:"varint,9,opt,name=min_stock,json=minStock,proto3,oneof" json:"min_stock,omitempty"`
	MaxStock         *int32                 `protobuf:"varint,10,opt,name=max_stock,json=maxStock,proto3,oneof" json:"max_stock,omitempty"`
	Category         *string                `protobuf:"bytes,11,opt,name=category,proto3,oneof" json:"category,omitempty"`
	SubCategory      *string                `protobuf:"bytes,12,opt,name=sub_category,json=subCategory,proto3,oneof" json:"sub_category,omitempty"`
	Brand            *string                `protobuf:"bytes,13,opt,name=brand,proto3,oneof" json:"brand,omitempty"`
	Barcode          *string                `protobuf:"bytes,14,opt,name=barcode,proto3,oneof" json:"barcode,omitempty"`
	Weight           *float64               `protobuf:"fixed64,15,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Dimensions       *string                `protobuf:"bytes,16,opt,name=dimensions,proto3,oneof" json:"dimensions,omitempty"`
	Color            *string                `protobuf:"bytes,17,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Size             *string                `protobuf:"bytes,18,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Material         *string                `protobuf:"bytes,19,opt,name=material,proto3,oneof" json:"material,omitempty"`
	Tags             *string                `protobuf:"bytes,20,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	Images           *string                `protobuf:"bytes,21,opt,name=images,proto3,oneof" json:"images,omitempty"`
	IsActive         *bool                  `protobuf:"varint,22,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	IsDigital        *bool                  `protobuf:"varint,23,opt,name=is_digital,json=isDigital,proto3,oneof" json:"is_digital,omitempty"`
	IsFeatured       *bool                  `protobuf:"varint,24,opt,name=is_featured,json=isFeatured,proto3,oneof" json:"is_featured,omitempty"`
	IsOnSale         *bool                  `protobuf:"varint,25,opt,name=is_on_sale,json=isOnSale,proto3,oneof" json:"is_on_sale,omitempty"`
	SortOrder        *int32                 `protobuf:"varint,26,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetShortDescription() string {
	if x != nil && x.ShortDescription != nil {
		return *x.ShortDescription
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetComparePrice() float64 {
	if x != nil && x.ComparePrice != nil {
		return *x.ComparePrice
	}
	return 0
}

func (x *UpdateProductRequest) GetCostPrice() float64 {
	if x != nil && x.CostPrice != nil {
		return *x.CostPrice
	}
	return 0
}

func (x *UpdateProductRequest) GetStock() int32 {
	if x != nil && x.Stock != nil {
		return *x.Stock
	}
	return 0
}

func (x *UpdateProductRequest) GetMinStock() int32 {
	if x != nil && x.MinStock != nil {
		return *x.MinStock
	}
	return 0
}

func (x *UpdateProductRequest) GetMaxStock() int32 {
	if x != nil && x.MaxStock != nil {
		return *x.MaxStock
	}
	return 0
}

func (x *UpdateProductRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *UpdateProductRequest) GetSubCategory() string {
	if x != nil && x.SubCategory != nil {
		return *x.SubCategory
	}
	return ""
}

func (x *UpdateProductRequest) GetBrand() string {
	if x != nil && x.Brand != nil {
		return *x.Brand
	}
	return ""
}

func (x *UpdateProductRequest) GetBarcode() string {
	if x != nil && x.Barcode != nil {
		return *x.Barcode
	}
	return ""
}

func (x *UpdateProductRequest) GetWeight() float64 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *UpdateProductRequest) GetDimensions() string {
	if x != nil && x.Dimensions != nil {
		return *x.Dimensions
	}
	return ""
}

func (x *UpdateProductRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *UpdateProductRequest) GetSize() string {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return ""
}

func (x *UpdateProductRequest) GetMaterial() string {
	if x != nil && x.Material != nil {
		return *x.Material
	}
	return ""
}

func (x *UpdateProductRequest) GetTags() string {
	if x != nil && x.Tags != nil {
		return *x.Tags
	}
	return ""
}

func (x *UpdateProductRequest) GetImages() string {
	if x != nil && x.Images != nil {
		return *x.Images
	}
	return ""
}

func (x *UpdateProductRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *UpdateProductRequest) GetIsDigital() bool {
	if x != nil && x.IsDigital != nil {
		return *x.IsDigital
	}
	return false
}

func (x *UpdateProductRequest) GetIsFeatured() bool {
	if x != nil && x.IsFeatured != nil {
		return *x.IsFeatured
	}
	return false
}

func (x *UpdateProductRequest) GetIsOnSale() bool {
	if x != nil && x.IsOnSale != nil {
		return *x.IsOnSale
	}
	return false
}

func (x *UpdateProductRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

// DeleteProduct messages
type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProductRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_api_proto_product_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListProducts messages
type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{8}
}

func (x *ListProductsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_api_proto_product_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{9}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListProductsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchProducts messages
type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	IsActive      *bool                  `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	IsDigital     *bool                  `protobuf:"varint,7,opt,name=is_digital,json=isDigital,proto3,oneof" json:"is_digital,omitempty"`
	IsFeatured    *bool                  `protobuf:"varint,8,opt,name=is_featured,json=isFeatured,proto3,oneof" json:"is_featured,omitempty"`
	IsOnSale      *bool                  `protobuf:"varint,9,opt,name=is_on_sale,json=isOnSale,proto3,oneof" json:"is_on_sale,omitempty"`
	Offset        int32                  `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{10}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchProductsRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *SearchProductsRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchProductsRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchProductsRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *SearchProductsRequest) GetIsDigital() bool {
	if x != nil && x.IsDigital != nil {
		return *x.IsDigital
	}
	return false
}

func (x *SearchProductsRequest) GetIsFeatured() bool {
	if x != nil && x.IsFeatured != nil {
		return *x.IsFeatured
	}
	return false
}

func (x *SearchProductsRequest) GetIsOnSale() bool {
	if x != nil && x.IsOnSale != nil {
		return *x.IsOnSale
	}
	return false
}

func (x *SearchProductsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListProductsByCategory messages
type ListProductsByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsByCategoryRequest) Reset() {
	*x = ListProductsByCategoryRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsByCategoryRequest) ProtoMessage() {}

func (x *ListProductsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*ListProductsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{11}
}

func (x *ListProductsByCategoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListProductsByCategoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListProductsByCategoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Stock management messages
type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateStockRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateStockRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_api_proto_product_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReduceStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceStockRequest) Reset() {
	*x = ReduceStockRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceStockRequest) ProtoMessage() {}

func (x *ReduceStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceStockRequest.ProtoReflect.Descriptor instead.
func (*ReduceStockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{14}
}

func (x *ReduceStockRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReduceStockRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ReduceStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceStockResponse) Reset() {
	*x = ReduceStockResponse{}
	mi := &file_api_proto_product_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceStockResponse) ProtoMessage() {}

func (x *ReduceStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceStockResponse.ProtoReflect.Descriptor instead.
func (*ReduceStockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{15}
}

func (x *ReduceStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IncreaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseStockRequest) Reset() {
	*x = IncreaseStockRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStockRequest) ProtoMessage() {}

func (x *IncreaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStockRequest.ProtoReflect.Descriptor instead.
func (*IncreaseStockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{16}
}

func (x *IncreaseStockRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *IncreaseStockRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type IncreaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseStockResponse) Reset() {
	*x = IncreaseStockResponse{}
	mi := &file_api_proto_product_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStockResponse) ProtoMessage() {}

func (x *IncreaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStockResponse.ProtoReflect.Descriptor instead.
func (*IncreaseStockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{17}
}

func (x *IncreaseStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Product status management messages
type ActivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProductRequest) Reset() {
	*x = ActivateProductRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProductRequest) ProtoMessage() {}

func (x *ActivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProductRequest.ProtoReflect.Descriptor instead.
func (*ActivateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{18}
}

func (x *ActivateProductRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeactivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductRequest) Reset() {
	*x = DeactivateProductRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductRequest) ProtoMessage() {}

func (x *DeactivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductRequest.ProtoReflect.Descriptor instead.
func (*DeactivateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{19}
}

func (x *DeactivateProductRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type MarkAsFeaturedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsFeaturedRequest) Reset() {
	*x = MarkAsFeaturedRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsFeaturedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsFeaturedRequest) ProtoMessage() {}

func (x *MarkAsFeaturedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsFeaturedRequest.ProtoReflect.Descriptor instead.
func (*MarkAsFeaturedRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{20}
}

func (x *MarkAsFeaturedRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type UnmarkAsFeaturedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmarkAsFeaturedRequest) Reset() {
	*x = UnmarkAsFeaturedRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmarkAsFeaturedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmarkAsFeaturedRequest) ProtoMessage() {}

func (x *UnmarkAsFeaturedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmarkAsFeaturedRequest.ProtoReflect.Descriptor instead.
func (*UnmarkAsFeaturedRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{21}
}

func (x *UnmarkAsFeaturedRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type IncrementViewCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementViewCountRequest) Reset() {
	*x = IncrementViewCountRequest{}
	mi := &file_api_proto_product_product_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementViewCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementViewCountRequest) ProtoMessage() {}

func (x *IncrementViewCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementViewCountRequest.ProtoReflect.Descriptor instead.
func (*IncrementViewCountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{22}
}

func (x *IncrementViewCountRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type IncrementViewCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementViewCountResponse) Reset() {
	*x = IncrementViewCountResponse{}
	mi := &file_api_proto_product_product_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementViewCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementViewCountResponse) ProtoMessage() {}

func (x *IncrementViewCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_product_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementViewCountResponse.ProtoReflect.Descriptor instead.
func (*IncrementViewCountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_product_product_proto_rawDescGZIP(), []int{23}
}

func (x *IncrementViewCountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_product_product_proto protoreflect.FileDescriptor

const file_api_proto_product_product_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/product/product.proto\x12\aproduct\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\a\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\x11short_description\x18\x04 \x01(\tR\x10shortDescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12#\n" +
	"\rcompare_price\x18\x06 \x01(\x01R\fcomparePrice\x12\x1d\n" +
	"\n" +
	"cost_price\x18\a \x01(\x01R\tcostPrice\x12\x14\n" +
	"\x05stock\x18\b \x01(\x05R\x05stock\x12\x1b\n" +
	"\tmin_stock\x18\t \x01(\x05R\bminStock\x12\x1b\n" +
	"\tmax_stock\x18\n" +
	" \x01(\x05R\bmaxStock\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\f \x01(\tR\vsubCategory\x12\x14\n" +
	"\x05brand\x18\r \x01(\tR\x05brand\x12\x10\n" +
	"\x03sku\x18\x0e \x01(\tR\x03sku\x12\x18\n" +
	"\abarcode\x18\x0f \x01(\tR\abarcode\x12\x16\n" +
	"\x06weight\x18\x10 \x01(\x01R\x06weight\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x11 \x01(\tR\n" +
	"dimensions\x12\x14\n" +
	"\x05color\x18\x12 \x01(\tR\x05color\x12\x12\n" +
	"\x04size\x18\x13 \x01(\tR\x04size\x12\x1a\n" +
	"\bmaterial\x18\x14 \x01(\tR\bmaterial\x12\x12\n" +
	"\x04tags\x18\x15 \x01(\tR\x04tags\x12\x16\n" +
	"\x06images\x18\x16 \x01(\tR\x06images\x12\x1b\n" +
	"\tis_active\x18\x17 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"is_digital\x18\x18 \x01(\bR\tisDigital\x12\x1f\n" +
	"\vis_featured\x18\x19 \x01(\bR\n" +
	"isFeatured\x12\x1c\n" +
	"\n" +
	"is_on_sale\x18\x1a \x01(\bR\bisOnSale\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x1b \x01(\x05R\tsortOrder\x12\x1d\n" +
	"\n" +
	"view_count\x18\x1c \x01(\x05R\tviewCount\x129\n" +
	"\n" +
	"created_at\x18\x1d \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcb\x05\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12+\n" +
	"\x11short_description\x18\x03 \x01(\tR\x10shortDescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12#\n" +
	"\rcompare_price\x18\x05 \x01(\x01R\fcomparePrice\x12\x1d\n" +
	"\n" +
	"cost_price\x18\x06 \x01(\x01R\tcostPrice\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x1b\n" +
	"\tmin_stock\x18\b \x01(\x05R\bminStock\x12\x1b\n" +
	"\tmax_stock\x18\t \x01(\x05R\bmaxStock\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\v \x01(\tR\vsubCategory\x12\x14\n" +
	"\x05brand\x18\f \x01(\tR\x05brand\x12\x10\n" +
	"\x03sku\x18\r \x01(\tR\x03sku\x12\x18\n" +
	"\abarcode\x18\x0e \x01(\tR\abarcode\x12\x16\n" +
	"\x06weight\x18\x0f \x01(\x01R\x06weight\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x10 \x01(\tR\n" +
	"dimensions\x12\x14\n" +
	"\x05color\x18\x11 \x01(\tR\x05color\x12\x12\n" +
	"\x04size\x18\x12 \x01(\tR\x04size\x12\x1a\n" +
	"\bmaterial\x18\x13 \x01(\tR\bmaterial\x12\x12\n" +
	"\x04tags\x18\x14 \x01(\tR\x04tags\x12\x16\n" +
	"\x06images\x18\x15 \x01(\tR\x06images\x12\x1d\n" +
	"\n" +
	"is_digital\x18\x16 \x01(\bR\tisDigital\x12\x1f\n" +
	"\vis_featured\x18\x17 \x01(\bR\n" +
	"isFeatured\x12\x1c\n" +
	"\n" +
	"is_on_sale\x18\x18 \x01(\bR\bisOnSale\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x19 \x01(\x05R\tsortOrder\"=\n" +
	"\x0fProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"*\n" +
	"\x16GetProductBySKURequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\"\xb0\t\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x120\n" +
	"\x11short_description\x18\x04 \x01(\tH\x02R\x10shortDescription\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x05 \x01(\x01H\x03R\x05price\x88\x01\x01\x12(\n" +
	"\rcompare_price\x18\x06 \x01(\x01H\x04R\fcomparePrice\x88\x01\x01\x12\"\n" +
	"\n" +
	"cost_price\x18\a \x01(\x01H\x05R\tcostPrice\x88\x01\x01\x12\x19\n" +
	"\x05stock\x18\b \x01(\x05H\x06R\x05stock\x88\x01\x01\x12 \n" +
	"\tmin_stock\x18\t \x01(\x05H\aR\bminStock\x88\x01\x01\x12 \n" +
	"\tmax_stock\x18\n" +
	" \x01(\x05H\bR\bmaxStock\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\v \x01(\tH\tR\bcategory\x88\x01\x01\x12&\n" +
	"\fsub_category\x18\f \x01(\tH\n" +
	"R\vsubCategory\x88\x01\x01\x12\x19\n" +
	"\x05brand\x18\r \x01(\tH\vR\x05brand\x88\x01\x01\x12\x1d\n" +
	"\abarcode\x18\x0e \x01(\tH\fR\abarcode\x88\x01\x01\x12\x1b\n" +
	"\x06weight\x18\x0f \x01(\x01H\rR\x06weight\x88\x01\x01\x12#\n" +
	"\n" +
	"dimensions\x18\x10 \x01(\tH\x0eR\n" +
	"dimensions\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x11 \x01(\tH\x0fR\x05color\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x12 \x01(\tH\x10R\x04size\x88\x01\x01\x12\x1f\n" +
	"\bmaterial\x18\x13 \x01(\tH\x11R\bmaterial\x88\x01\x01\x12\x17\n" +
	"\x04tags\x18\x14 \x01(\tH\x12R\x04tags\x88\x01\x01\x12\x1b\n" +
	"\x06images\x18\x15 \x01(\tH\x13R\x06images\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x16 \x01(\bH\x14R\bisActive\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_digital\x18\x17 \x01(\bH\x15R\tisDigital\x88\x01\x01\x12$\n" +
	"\vis_featured\x18\x18 \x01(\bH\x16R\n" +
	"isFeatured\x88\x01\x01\x12!\n" +
	"\n" +
	"is_on_sale\x18\x19 \x01(\bH\x17R\bisOnSale\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\x1a \x01(\x05H\x18R\tsortOrder\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x14\n" +
	"\x12_short_descriptionB\b\n" +
	"\x06_priceB\x10\n" +
	"\x0e_compare_priceB\r\n" +
	"\v_cost_priceB\b\n" +
	"\x06_stockB\f\n" +
	"\n" +
	"_min_stockB\f\n" +
	"\n" +
	"_max_stockB\v\n" +
	"\t_categoryB\x0f\n" +
	"\r_sub_categoryB\b\n" +
	"\x06_brandB\n" +
	"\n" +
	"\b_barcodeB\t\n" +
	"\a_weightB\r\n" +
	"\v_dimensionsB\b\n" +
	"\x06_colorB\a\n" +
	"\x05_sizeB\v\n" +
	"\t_materialB\a\n" +
	"\x05_tagsB\t\n" +
	"\a_imagesB\f\n" +
	"\n" +
	"_is_activeB\r\n" +
	"\v_is_digitalB\x0e\n" +
	"\f_is_featuredB\r\n" +
	"\v_is_on_saleB\r\n" +
	"\v_sort_order\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"1\n" +
	"\x15DeleteProductResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"C\n" +
	"\x13ListProductsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x88\x01\n" +
	"\x14ListProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x92\x03\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x01R\bmaxPrice\x12 \n" +
	"\tis_active\x18\x06 \x01(\bH\x00R\bisActive\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_digital\x18\a \x01(\bH\x01R\tisDigital\x88\x01\x01\x12$\n" +
	"\vis_featured\x18\b \x01(\bH\x02R\n" +
	"isFeatured\x88\x01\x01\x12!\n" +
	"\n" +
	"is_on_sale\x18\t \x01(\bH\x03R\bisOnSale\x88\x01\x01\x12\x16\n" +
	"\x06offset\x18\n" +
	" \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\v \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_is_activeB\r\n" +
	"\v_is_digitalB\x0e\n" +
	"\f_is_featuredB\r\n" +
	"\v_is_on_sale\"i\n" +
	"\x1dListProductsByCategoryRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"I\n" +
	"\x12UpdateStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock\"/\n" +
	"\x13UpdateStockResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"K\n" +
	"\x12ReduceStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"/\n" +
	"\x13ReduceStockResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"M\n" +
	"\x14IncreaseStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"1\n" +
	"\x15IncreaseStockResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"7\n" +
	"\x16ActivateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\"9\n" +
	"\x18DeactivateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\"6\n" +
	"\x15MarkAsFeaturedRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\"8\n" +
	"\x17UnmarkAsFeaturedRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\":\n" +
	"\x19IncrementViewCountRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\"6\n" +
	"\x1aIncrementViewCountResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x84\n" +
	"\n" +
	"\x0eProductService\x12H\n" +
	"\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x18.product.ProductResponse\x12B\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x18.product.ProductResponse\x12L\n" +
	"\x0fGetProductBySKU\x12\x1f.product.GetProductBySKURequest\x1a\x18.product.ProductResponse\x12H\n" +
	"\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x18.product.ProductResponse\x12N\n" +
	"\rDeleteProduct\x12\x1d.product.DeleteProductRequest\x1a\x1e.product.DeleteProductResponse\x12K\n" +
	"\fListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\x12O\n" +
	"\x0eSearchProducts\x12\x1e.product.SearchProductsRequest\x1a\x1d.product.ListProductsResponse\x12_\n" +
	"\x16ListProductsByCategory\x12&.product.ListProductsByCategoryRequest\x1a\x1d.product.ListProductsResponse\x12H\n" +
	"\vUpdateStock\x12\x1b.product.UpdateStockRequest\x1a\x1c.product.UpdateStockResponse\x12H\n" +
	"\vReduceStock\x12\x1b.product.ReduceStockRequest\x1a\x1c.product.ReduceStockResponse\x12N\n" +
	"\rIncreaseStock\x12\x1d.product.IncreaseStockRequest\x1a\x1e.product.IncreaseStockResponse\x12L\n" +
	"\x0fActivateProduct\x12\x1f.product.ActivateProductRequest\x1a\x18.product.ProductResponse\x12P\n" +
	"\x11DeactivateProduct\x12!.product.DeactivateProductRequest\x1a\x18.product.ProductResponse\x12J\n" +
	"\x0eMarkAsFeatured\x12\x1e.product.MarkAsFeaturedRequest\x1a\x18.product.ProductResponse\x12N\n" +
	"\x10UnmarkAsFeatured\x12 .product.UnmarkAsFeaturedRequest\x1a\x18.product.ProductResponse\x12]\n" +
	"\x12IncrementViewCount\x12\".product.IncrementViewCountRequest\x1a#.product.IncrementViewCountResponseB2Z0github.com/ddd-micro/api/proto/product;productpbb\x06proto3"

var (
	file_api_proto_product_product_proto_rawDescOnce sync.Once
	file_api_proto_product_product_proto_rawDescData []byte
)

func file_api_proto_product_product_proto_rawDescGZIP() []byte {
	file_api_proto_product_product_proto_rawDescOnce.Do(func() {
		file_api_proto_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_product_product_proto_rawDesc), len(file_api_proto_product_product_proto_rawDesc)))
	})
	return file_api_proto_product_product_proto_rawDescData
}

var file_api_proto_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_product_product_proto_goTypes = []any{
	(*Product)(nil),                       // 0: product.Product
	(*CreateProductRequest)(nil),          // 1: product.CreateProductRequest
	(*ProductResponse)(nil),               // 2: product.ProductResponse
	(*GetProductRequest)(nil),             // 3: product.GetProductRequest
	(*GetProductBySKURequest)(nil),        // 4: product.GetProductBySKURequest
	(*UpdateProductRequest)(nil),          // 5: product.UpdateProductRequest
	(*DeleteProductRequest)(nil),          // 6: product.DeleteProductRequest
	(*DeleteProductResponse)(nil),         // 7: product.DeleteProductResponse
	(*ListProductsRequest)(nil),           // 8: product.ListProductsRequest
	(*ListProductsResponse)(nil),          // 9: product.ListProductsResponse
	(*SearchProductsRequest)(nil),         // 10: product.SearchProductsRequest
	(*ListProductsByCategoryRequest)(nil), // 11: product.ListProductsByCategoryRequest
	(*UpdateStockRequest)(nil),            // 12: product.UpdateStockRequest
	(*UpdateStockResponse)(nil),           // 13: product.UpdateStockResponse
	(*ReduceStockRequest)(nil),            // 14: product.ReduceStockRequest
	(*ReduceStockResponse)(nil),           // 15: product.ReduceStockResponse
	(*IncreaseStockRequest)(nil),          // 16: product.IncreaseStockRequest
	(*IncreaseStockResponse)(nil),         // 17: product.IncreaseStockResponse
	(*ActivateProductRequest)(nil),        // 18: product.ActivateProductRequest
	(*DeactivateProductRequest)(nil),      // 19: product.DeactivateProductRequest
	(*MarkAsFeaturedRequest)(nil),         // 20: product.MarkAsFeaturedRequest
	(*UnmarkAsFeaturedRequest)(nil),       // 21: product.UnmarkAsFeaturedRequest
	(*IncrementViewCountRequest)(nil),     // 22: product.IncrementViewCountRequest
	(*IncrementViewCountResponse)(nil),    // 23: product.IncrementViewCountResponse
	(*timestamppb.Timestamp)(nil),         // 24: google.protobuf.Timestamp
}
var file_api_proto_product_product_proto_depIdxs = []int32{
	24, // 0: product.Product.created_at:type_name -> google.protobuf.Timestamp
	24, // 1: product.Product.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: product.ProductResponse.product:type_name -> product.Product
	0,  // 3: product.ListProductsResponse.products:type_name -> product.Product
	1,  // 4: product.ProductService.CreateProduct:input_type -> product.CreateProductRequest
	3,  // 5: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	4,  // 6: product.ProductService.GetProductBySKU:input_type -> product.GetProductBySKURequest
	5,  // 7: product.ProductService.UpdateProduct:input_type -> product.UpdateProductRequest
	6,  // 8: product.ProductService.DeleteProduct:input_type -> product.DeleteProductRequest
	8,  // 9: product.ProductService.ListProducts:input_type -> product.ListProductsRequest
	10, // 10: product.ProductService.SearchProducts:input_type -> product.SearchProductsRequest
	11, // 11: product.ProductService.ListProductsByCategory:input_type -> product.ListProductsByCategoryRequest
	12, // 12: product.ProductService.UpdateStock:input_type -> product.UpdateStockRequest
	14, // 13: product.ProductService.ReduceStock:input_type -> product.ReduceStockRequest
	16, // 14: product.ProductService.IncreaseStock:input_type -> product.IncreaseStockRequest
	18, // 15: product.ProductService.ActivateProduct:input_type -> product.ActivateProductRequest
	19, // 16: product.ProductService.DeactivateProduct:input_type -> product.DeactivateProductRequest
	20, // 17: product.ProductService.MarkAsFeatured:input_type -> product.MarkAsFeaturedRequest
	21, // 18: product.ProductService.UnmarkAsFeatured:input_type -> product.UnmarkAsFeaturedRequest
	22, // 19: product.ProductService.IncrementViewCount:input_type -> product.IncrementViewCountRequest
	2,  // 20: product.ProductService.CreateProduct:output_type -> product.ProductResponse
	2,  // 21: product.ProductService.GetProduct:output_type -> product.ProductResponse
	2,  // 22: product.ProductService.GetProductBySKU:output_type -> product.ProductResponse
	2,  // 23: product.ProductService.UpdateProduct:output_type -> product.ProductResponse
	7,  // 24: product.ProductService.DeleteProduct:output_type -> product.DeleteProductResponse
	9,  // 25: product.ProductService.ListProducts:output_type -> product.ListProductsResponse
	9,  // 26: product.ProductService.SearchProducts:output_type -> product.ListProductsResponse
	9,  // 27: product.ProductService.ListProductsByCategory:output_type -> product.ListProductsResponse
	13, // 28: product.ProductService.UpdateStock:output_type -> product.UpdateStockResponse
	15, // 29: product.ProductService.ReduceStock:output_type -> product.ReduceStockResponse
	17, // 30: product.ProductService.IncreaseStock:output_type -> product.IncreaseStockResponse
	2,  // 31: product.ProductService.ActivateProduct:output_type -> product.ProductResponse
	2,  // 32: product.ProductService.DeactivateProduct:output_type -> product.ProductResponse
	2,  // 33: product.ProductService.MarkAsFeatured:output_type -> product.ProductResponse
	2,  // 34: product.ProductService.UnmarkAsFeatured:output_type -> product.ProductResponse
	23, // 35: product.ProductService.IncrementViewCount:output_type -> product.IncrementViewCountResponse
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_product_product_proto_init() }
func file_api_proto_product_product_proto_init() {
	if File_api_proto_product_product_proto != nil {
		return
	}
	file_api_proto_product_product_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_proto_product_product_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_product_product_proto_rawDesc), len(file_api_proto_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_product_product_proto_goTypes,
		DependencyIndexes: file_api_proto_product_product_proto_depIdxs,
		MessageInfos:      file_api_proto_product_product_proto_msgTypes,
	}.Build()
	File_api_proto_product_product_proto = out.File
	file_api_proto_product_product_proto_goTypes = nil
	file_api_proto_product_product_proto_depIdxs = nil
}
