name: Ansible Configuration Management

on:
  push:
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible.yml'
  pull_request:
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible.yml'

permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'
        
    - name: Install Ansible
      run: |
        pip install ansible ansible-lint
        
    - name: Run ansible-lint
      run: |
        ansible-lint ansible/playbooks/*.yml
        ansible-lint ansible/roles/*/

  ansible-syntax-check:
    name: Ansible Syntax Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'
        
    - name: Install Ansible
      run: |
        pip install ansible
        
    - name: Ansible syntax check
      run: |
        ansible-playbook --syntax-check ansible/playbooks/site.yml
        ansible-playbook --syntax-check ansible/playbooks/k8s-setup.yml
        ansible-playbook --syntax-check ansible/playbooks/deploy-apps.yml

  ansible-test:
    name: Ansible Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install ansible molecule[docker] pytest-testinfra
        
    - name: Run molecule tests
      run: |
        cd ansible/roles/k8s-setup
        molecule test
      continue-on-error: true

  ansible-dry-run:
    name: Ansible Dry Run
    runs-on: ubuntu-latest
    needs: [ansible-lint, ansible-syntax-check]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'
        
    - name: Install Ansible
      run: |
        pip install ansible
        
    - name: Create test inventory
      run: |
        cat > test-inventory.yml << EOF
        all:
          children:
            k8s_masters:
              hosts:
                localhost:
                  ansible_connection: local
                  ansible_python_interpreter: python3
            k8s_workers:
              hosts:
                localhost:
                  ansible_connection: local
                  ansible_python_interpreter: python3
        EOF
        
    - name: Ansible dry run
      run: |
        ansible-playbook --check --diff ansible/playbooks/site.yml -i test-inventory.yml
