name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write
  issues: write

jobs:
  dependabot:
    name: Dependabot Auto-merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.23'
        
    - name: Install Go dependencies
      run: go mod download
        
    - name: Run Go build
      run: go build ./...
        
    - name: Auto-merge Dependabot PR
      run: |
        gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
